# Generated by Django 5.2.6 on 2025-09-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="descriptions",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="updates_at",
            new_name="updated_at",
        ),
    ]
