# Generated by Django 5.2.6 on 2025-10-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": (("can_unpublish_product", "can unpublish product"),),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("draft", "Черновик"), ("published", "Опубликован")],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="Статус публикации",
            ),
        ),
    ]
